# Generated by Django 2.2.6 on 2021-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210309_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите Ваш текст', verbose_name='Текст'),
        ),
    ]
