# Generated by Django 2.2.6 on 2021-03-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
    ]
